[build]
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/boutique"
  to = "/pages/boutique.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/pages/about.html"
  status = 200

[[redirects]]
  from = "/bespoke"
  to = "/pages/bespoke.html"
  status = 200

[[redirects]]
  from = "/journal"
  to = "/pages/journal.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/pages/faq.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/pages/contact.html"
  status = 200
